name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.4
  - pip:
    - numpy
    - uvicorn
    - sqlalchemy
    - fastapi
    - torch
    - torchvision
    - torchaudio
    - pysoundfile==0.9.0
    - pyjwt
    - pydantic
    - passlib
    - fastapi-mail==1.0.8
    - python-dotenv
    - pydub
    - bcrypt
    - librosa
    - matplotlib
    - pandas
    - PyWavelets
    - transformers