"""Added network model

Revision ID: a01a8467150b
Revises: 76fca7668e12
Create Date: 2023-10-03 13:20:36.640008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01a8467150b'
down_revision: Union[str, None] = '76fca7668e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.String(), nullable=True),
    sa.Column('date_updated', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_id'), 'networks', ['id'], unique=False)
    op.create_index(op.f('ix_networks_is_active'), 'networks', ['is_active'], unique=False)
    op.create_index(op.f('ix_networks_name'), 'networks', ['name'], unique=False)
    op.create_index(op.f('ix_networks_status'), 'networks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networks_status'), table_name='networks')
    op.drop_index(op.f('ix_networks_name'), table_name='networks')
    op.drop_index(op.f('ix_networks_is_active'), table_name='networks')
    op.drop_index(op.f('ix_networks_id'), table_name='networks')
    op.drop_table('networks')
    # ### end Alembic commands ###
